default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1

development:
  <<: *default
  database: v360_todo_dev
  username: <%= ENV["DB_USERNAME"] || "v360_todo" %>
  password: <%= ENV["DB_PASSWORD"] || "123pass321" %>

test:
  <<: *default
  database: v360_todo_test
  username: <%= ENV["DB_USERNAME"] || "v360_todo" %>
  password: <%= ENV["DB_PASSWORD"] || "123pass321" %>

production:
  <<: *default
  database: v360_todo_production
  username: <%= ENV["DB_USERNAME"] || "v360_todo" %>
  password: <%= ENV["DB_PASSWORD"] || "123pass321" %>
