swagger: "2.0"
info:
  version: "1.0.0"
  title: "EndDo dev case v360 API"
  description: "Documentação da API para gerenciar listas de tarefas e itens associados."
host: "localhost:3000"
basePath: "/"
schemes:
  - "http"

paths:
  /lists:
    get:
      summary: "Listar todas as listas"
      description: "Retorna todas as listas de TO-DO cadastradas."
      tags:
        - "Lists"
      responses:
        200:
          description: "Listas retornadas com sucesso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/List"
    post:
      summary: "Criar uma nova lista"
      description: "Adiciona uma nova lista de TO-DO."
      tags:
        - "Lists"
      parameters:
        - in: "body"
          name: "body"
          description: "Dados da nova lista"
          required: true
          schema:
            $ref: "#/definitions/NewList"
      responses:
        201:
          description: "Lista criada com sucesso"
          schema:
            $ref: "#/definitions/List"

  /lists/{id}:
    get:
      summary: "Obter detalhes de uma lista"
      description: "Retorna os detalhes de uma lista específica."
      tags:
        - "Lists"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da lista"
      responses:
        200:
          description: "Detalhes da lista retornados com sucesso"
          schema:
            $ref: "#/definitions/List"
    patch:
      summary: "Atualizar uma lista"
      description: "Atualiza os dados de uma lista existente."
      tags:
        - "Lists"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da lista"
        - in: "body"
          name: "body"
          description: "Dados atualizados da lista"
          required: true
          schema:
            $ref: "#/definitions/UpdateList"
      responses:
        200:
          description: "Lista atualizada com sucesso"
          schema:
            $ref: "#/definitions/List"
    delete:
      summary: "Excluir uma lista"
      description: "Remove uma lista pelo ID."
      tags:
        - "Lists"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da lista"
      responses:
        204:
          description: "Lista excluída com sucesso"

  /lists/{list_id}/items:
    get:
      summary: "Listar itens de uma lista"
      description: "Retorna todos os itens associados a uma lista específica."
      tags:
        - "Items"
      parameters:
        - name: "list_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da lista"
      responses:
        200:
          description: "Itens retornados com sucesso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Item"
    post:
      summary: "Adicionar um item a uma lista"
      description: "Cria um novo item associado a uma lista."
      tags:
        - "Items"
      parameters:
        - name: "list_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da lista"
        - in: "body"
          name: "body"
          description: "Dados do novo item"
          required: true
          schema:
            $ref: "#/definitions/NewItem"
      responses:
        201:
          description: "Item criado com sucesso"
          schema:
            $ref: "#/definitions/Item"

  /lists/{list_id}/items/{item_id}:
    patch:
      summary: "Atualizar um item"
      description: "Atualiza os dados de um item específico."
      tags:
        - "Items"
      parameters:
        - name: "list_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da lista"
        - name: "item_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID do item"
        - in: "body"
          name: "body"
          description: "Dados para atualizar o item"
          required: true
          schema:
            $ref: "#/definitions/UpdateItem"
      responses:
        200:
          description: "Item atualizado com sucesso"
          schema:
            $ref: "#/definitions/Item"
    delete:
      summary: "Excluir um item"
      description: "Remove um item pelo ID."
      tags:
        - "Items"
      parameters:
        - name: "list_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da lista"
        - name: "item_id"
          in: "path"
          required: true
          type: "integer"
          description: "ID do item"
      responses:
        204:
          description: "Item excluído com sucesso"

definitions:
  List:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      priority:
        type: "string"
      category:
        type: "string"
      completed:
        type: "boolean"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
  NewList:
    type: "object"
    required:
      - "title"
    properties:
      title:
        type: "string"
      priority:
        type: "string"
      category:
        type: "string"
      completed:
        type: "boolean"
  UpdateList:
    type: "object"
    properties:
      title:
        type: "string"
      priority:
        type: "string"
      category:
        type: "string"
      completed:
        type: "boolean"
  Item:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      description:
        type: "string"
      completed:
        type: "boolean"
      category:
        type: "string"
      due_date:
        type: "string"
        format: "date"
      list_id:
        type: "integer"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"
  NewItem:
    type: "object"
    required:
      - "title"
      - "description"
      - "category"
      - "due_date"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      completed:
        type: "boolean"
      category:
        type: "string"
      due_date:
        type: "string"
        format: "date"
  UpdateItem:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      completed:
        type: "boolean"
      category:
        type: "string"
      due_date:
        type: "string"
        format: "date"
